name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DPDK_VERSION: 22.11.4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt update && sudo apt install -y linux-headers-amd64 build-essential libnuma-dev git meson python3-pyelftools curl libclang-dev clang llvm-dev
    - name: Install DPDK
      run: |
          wget -O dpdk.tar.xz https://fast.dpdk.org/rel/dpdk-${DPDK_VERSION}.tar.xz && tar -xvJf dpdk.tar.xz
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
